using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

// CREDIT: https://github.com/Hopeless404/WildFrostHopeMods

namespace WFExtraBattles.Util
{
    public class Tables
    {

        public static Dictionary<string, string>
            Cards = new Dictionary<string, string>() {
        {"Baby Snowbo", "BabySnowbo"},
        {"Bom Barrel", "Badoo"},
        {"Scaven", "Bear"},
        {"Beepop", "Beepop"},
        {"Beepop Mask", "BeepopMask"},
        {"Plum", "Berro"},
        {"Berry Basket", "BerryBasket"},
        {"Berry Blade", "BerryBlade"},
        {"Earth Berry", "BerryMonster"},
        {"Booshu", "BerryPet"},
        {"Berry Witch", "BerryWitch"},
        {"Big Berry", "BigBerry"},
        {"Big Peng", "BigPeng"},
        {"Bitebox", "Bitebox"},
        {"Blaze Tea", "BlazeTea"},
        {"Bling Bank", "Blingo"},
        {"Supersnower", "BlizzPop"},
        {"Krab", "Blockhead"},
        {"Berry Sis", "BloodBoy"},
        {"Blunky", "Blunky"},
        {"Van Jun", "BoBo"},
        {"Groff", "Boggler"},
        {"Bolgo", "Bolgo"},
        {"Azul Battle Axe", "BoltHarpoon"},
        {"Bombom", "Bombom"},
        {"Portable Workbench", "Bonfire"},
        {"Bonnie", "Bonnie"},
        {"Lil' Gazi", "BoostPet"},
        {"Broken Vase", "BrokenVase"},
        {"Bulbhead", "BulbHead"},
        {"Blaze Bom", "Bumblebee"},
        {"Bumbo", "Bumbo"},
        {"Kreggo", "Bunnight"},
        {"Willow", "Burner"},
        {"Burster", "Burster"},
        {"Chompom", "Chompom"},
        {"Chungoon", "Chungoon"},
        {"Grumps", "Chunky"},
        {"Krunker", "ClunkerBoss"},
        {"Krunker", "ClunkerBoss2"},
        {"Smog", "Confuddler"},
        {"Conker", "Conker"},
        {"Razor", "CrazyEyes"},
        {"Proto-Stomper", "Crowbar"},
        {"Tar Blade", "Dart"},
        {"Demonheart", "Demonheart"},
        {"Loki", "DemonPet"},
        {"Dimona", "Dimona"},
        {"Splinter", "Ditto"},
        {"Blank Mask", "Dittostone"},
        {"Dragon Pepper", "DragonflamePepper"},
        {"Sneezle", "DrawPet"},
        {"Dregg", "Dregg"},
        {"Egg", "Egg"},
        {"Shade Wisp", "EnemyCloner"},
        {"Clockwork Bom", "EnergyDart"},
        {"Magma Booster", "EyeDrops"},
        {"Fallow", "Fallow"},
        {"Fallow Mask", "FallowMask"},
        {"Frost Guardian", "FinalBoss"},
        {"Frost Guardian", "FinalBoss2"},
        {"Firefist", "Firefist"},
        {"Flamewater", "FlameWater"},
        {"Vesta", "Flash"},
        {"Azul Candle", "FlashWhip"},
        {"Foggy Brew", "FoggyBrew"},
        {"Foxee", "Foxee"},
        {"Infernoko", "FrenzyBoss"},
        {"Infernoko", "FrenzyBoss2"},
        {"Frenzy Wrench", "FrenzyShard"},
        {"Frost Bell", "FrostBell"},
        {"Frostbloom", "FrostBloom"},
        {"Frostinger", "Frostinger"},
        {"The Ringer", "Frosty"},
        {"Fungun", "Fungoose"},
        {"Gearhammer", "Gearhammer"},
        {"Folby", "Gearhead"},
        {"Fizzle", "Gnomlings"},
        {"Gobling", "Gobling"},
        {"Gok", "Gok"},
        {"Grink", "Grink"},
        {"Grog", "Grog"},
        {"Grouchy", "Grouchy"},
        {"Nom & Stompy", "GuardianGnome"},
        {"Muttonhead", "GukaGuka"},
        {"Haze Keg", "HazeBlaze"},
        {"Heartforge", "Heartforge"},
        {"Heartmist Station", "HeartmistStation"},
        {"Hongo's Hammer", "HongosHammer"},
        {"Grabber", "Hooker"},
        {"Ice Dice", "IceDice"},
        {"Ice Forge", "IceForge"},
        {"Krawler", "Icemason"},
        {"Frostbite Shard", "IceShard"},
        {"Jab Joat", "JabJoat"},
        {"Spike", "Jagzag"},
        {"Tootordion", "Joob"},
        {"Gigi's Gizmo", "Juicepot"},
        {"Tinkerson Jr.", "Jummo"},
        {"Gigi's Cookie Box", "Junberry"},
        {"Junjun Mask", "JunjunMask"},
        {"Junk", "Junk"},
        {"Junkhead", "Junkhead"},
        {"Blundertank", "Junkmuncher"},
        {"Kernel", "Kernel"},
        {"Jumbo", "Klutz"},
        {"Taiga", "Kokonut"},
        {"Krono", "Krono"},
        {"Leader", "Leader"},
        {"Leech", "Leech"},
        {"Leech Mask", "Leecher"},
        {"Lil' Berry", "LilBerry"},
        {"Lumin Goop", "LuminSealant"},
        {"Lumin Lantern", "LuminShard"},
        {"The Lumin Vase", "LuminVase"},
        {"Sunglass Chime", "Madness"},
        {"Makoko", "Makoko"},
        {"Mega Mimik", "MegaMimik"},
        {"Mimik", "Mimik"},
        {"Ice Lantern", "MiniForge"},
        {"Minimoko", "Minimoko"},
        {"Mobile Campfire", "MobileCampfire"},
        {"Molten Dip", "MoltenDip"},
        {"Monch", "Monch"},
        {"King Moko", "MonkeyKing"},
        {"Moko Head", "MonkeyWorshipTotem"},
        {"Bigloo", "Muttonhead"},
        {"Naked Gnome", "NakedGnome"},
        {"Naked Gnome", "NakedGnomeFriendly"},
        {"Gromble", "Noodle"},
        {"Noomlin Biscuit", "NoomlinBiscuit"},
        {"B.I.N.K", "Nullifier"},
        {"Numskull", "Numskull"},
        {"Nutshell Cake", "NutshellCake"},
        {"I.C.G.M", "OhNo"},
        {"Ooba Bear", "OobaBear"},
        {"Pecan", "Pecan"},
        {"Pengoon", "Pengoon"},
        {"Peppereaper", "Peppereaper"},
        {"Pepper Flag", "PepperFlag"},
        {"Peppering", "Peppering"},
        {"Moko Totem", "Peppermaton"},
        {"Pepper Witch", "PepperWitch"},
        {"Pom", "Pigeon"},
        {"Pom Mask", "PigeonCage"},
        {"Pinkberry Juice", "PinkberryJuice"},
        {"Junjun", "Plep"},
        {"Plinker", "Plinker"},
        {"Berry Bell", "Plum"},
        {"Gachapomper", "PomDispenser"},
        {"Pombomb", "PomegranateBomb"},
        {"Pootie", "Pootie"},
        {"Sheepopper", "Popper"},
        {"Sheepopper Mask", "PopPopper"},
        {"Popshroom", "Popshroom"},
        {"Prickle", "Prickle"},
        {"Puffball", "Puffball"},
        {"Shade Clay", "Putty"},
        {"Pygmy", "Pygmy"},
        {"Pyra", "Pyra"},
        {"Devicro", "Reaper"},
        {"Forging Stove", "Recycler"},
        {"Scrap Pile", "ScrapPile"},
        {"Skullmist Tea", "Scythe"},
        {"Tiger Skull", "SharkTooth"},
        {"Shellbo", "Shellbo"},
        {"Shell Shield", "ShellShield"},
        {"Shell Witch", "ShellWitch"},
        {"Shelly", "Shelly"},
        {"Shroom Gobbler", "ShroomGobbler"},
        {"Shroominator", "Shroominator"},
        {"Shroomine", "Shroomine"},
        {"Fungo Blaster", "ShroomLauncher"},
        {"Shrootles", "Shrootles"},
        {"Blizzard Bottle", "Shwooper"},
        {"Slapcrackers", "Slapcrackers"},
        {"Gogong", "Smackgoon"},
        {"Bigfoot", "Smakk"},
        {"Grizzle", "Sno"},
        {"Snobble", "Snobble"},
        {"Snoffel", "Snoffel"},
        {"Wild Snoolf", "Snoolf"},
        {"Winter Worm", "SnormWorm"},
        {"Snowbirb", "Snowbirb"},
        {"Snowbo", "Snowbo"},
        {"Snowcake", "Snowcake"},
        {"Snowzooka", "SnowCannon"},
        {"Kobonker", "Snowcracker"},
        {"Storm Globe", "SnowGlobe"},
        {"Snow Gobbler", "SnowGobbler"},
        {"The Snow Knight", "SnowKnight"},
        {"Yeti Skull", "SnowMaul"},
        {"Snow Stick", "SnowStick"},
        {"Spice Sparklers", "SpiceSparklers"},
        {"Spice Stones", "SpiceStones"},
        {"Spike Wall", "SpikeWall"},
        {"Bamboozle", "SplitBoss"},
        {"Bam", "SplitBoss1"},
        {"Boozle", "SplitBoss2"},
        {"Spore Pack", "SporePack"},
        {"Porkypine", "Sporkypine"},
        {"Spuncher", "Spuncher"},
        {"Marrow", "Spyke"},
        {"Paw Paw", "Stinghorn"},
        {"Stormbear Spirit", "StormbearSpirit"},
        {"Truffle", "SummonBoss"},
        {"Truffle", "SummonBoss2"},
        {"Truffle", "SummonBoss3"},
        {"Suncream", "SunberryJuice"},
        {"Sunburst Tootoo", "SunburstDart"},
        {"Sunlight Drum", "SunlightDrum"},
        {"Sun Rod", "SunRod"},
        {"Sunsong Box", "SunShard"},
        {"Scrappy Sword", "Sword"},
        {"Chikichi", "TailsFive"},
        {"Chikani", "TailsFour"},
        {"Chikagoru", "TailsOne"},
        {"Chikasan", "TailsThree"},
        {"Chikashi", "TailsTwo"},
        {"Tigris", "Tigris"},
        {"Tigris Mask", "TigrisMask"},
        {"Mini Mika", "Timmy"},
        {"Tiny Tyko", "TinyTyko"},
        {"Maw Jaw", "Toothless"},
        {"Totem of the Goat", "TotemOfTheGoat"},
        {"Frost Jailer", "TrueFinalBoss1"},
        {"Frost Crusher", "TrueFinalBoss2"},
        {"Frost Lancer", "TrueFinalBoss3"},
        {"Frost Bomber", "TrueFinalBoss4"},
        {"Frost Junker", "TrueFinalBoss5"},
        {"Frost Muncher", "TrueFinalBoss6"},
        {"Alloy", "Turmeep"},
        {"Queen Globerry", "Turnip"},
        {"Tusk", "Tusk"},
        {"Veiled Lady", "VeiledLady"},
        {"Haze Balloon", "Vimifier"},
        {"Bombarder", "Vimik"},
        {"Tentickle", "Voido"},
        {"Soulbound Skulls", "VoidStaff"},
        {"Flask of Ink", "Voidstone"},
        {"Hazeblazer", "Voodoo"},
        {"Bombarder", "Vox"},
        {"Waddlegoons", "Waddlegoons"},
        {"Wallop", "Wallop"},
        {"Rockhog", "Wally"},
        {"Hog", "Wildling"},
        {"Biji", "Witch"},
        {"Snoof", "Wolfie"},
        {"Woodhead", "Woodhead"},
        {"Woolly Drek", "WoollyDrek"},
        {"Wort", "Wort"},
        {"Warthog", "Wrecker"},
        {"Mini Muncher", "Wrenchy"},
        {"Yuki", "Yuki"},
        {"Azul Skull", "ZapOrb"},
        {"Shen", "Zoog"},
        };


        public static List<string>
            CardText = new List<string>()
        {
        "Deal additional damage equal to <Tar Blades> in hand",
        "Deal additional damage equal to {0}",
        "Deal additional damage equal to {0} on the board",
        "Deal damage equal to {0}",
        "Destroy self",
        "Double the target's {0}",
        "Restore {0}",
        "Increase {0} by <{a}>",
        "While damaged, {0} is increased by <{a}>",
        "Add their {0} to all allies",
        "Add {0}",
        "Add {0} to your hand",
        "Add {0} to a random ally",
        "Gain {0}",
        "Apply {0} to a random ally or enemy",
        "Apply {0} to a random enemy",
        "Apply {0} to front enemy",
        "Apply {0} to a random ally",
        "Apply {0} to all enemies",
        "Apply {0} to enemies in the row",
        "Deal <{a}> damage to all {e}'d enemies",
        "Deal <{a}> damage to self and allies in the row",
        "Deal <{a}> damage to all undamaged enemies",
        "Lose {0}",
        "Reduce by {0} when played",
        "Kill a random ally",
        "Take {e} from all allies",
        "Also hits ally behind",
        "Deal <{a}> additional damage to damaged targets",
        "Deal <{a}> additional damage to {e}'d targets",
        "Restore {0} to front ally equal to damage dealt ",
        "Apply {0} equal to damage dealt",
        "Gain {0} on kill",
        "On kill, apply {0} to all allies",
        "On kill, apply {0} to a random ally",
        "On kill, apply {0} to a random enemy",
        "Restore {0} on kill",
        "On kill, restore {0} to self and allies in the row",
        "Apply {0} to ally behind",
        "Apply {0} to all allies",
        "Apply {0} to ally ahead",
        "Eat a random ally, absorbing their <keyword=attack>, <keyword=health> and effects",
        "Escape from the battle",
        "Restore {0} to all allies",
        "Eat allies in the row, absorbing their <keyword=attack> and <keyword=health>",
        "Take {e} from a random ally in order to attack",
        "Count down {0} by <{a}>",
        "Reduce {0} by <{a}>",
        "Kill an ally",
        "Kill an enemy",
        "Summon {0}",
        "Summon {0} on the enemy side",
        "Trigger against the target when an ally attacks",
        "Trigger against anything that is hit with {e}",
        "Trigger when an ally attacks",
        "Trigger when an ally in the row attacks",
        "Trigger when an ally is hit",
        "When an ally is healed, apply equal {0}",
        "When an ally is hit, apply {0} to the attacker",
        "When an ally is hit, restore their {0} by <{a}>",
        "Gain {0} when an ally is killed",
        "When an ally is <keyword=sacrificed>, gain their {0}",
        "Trigger when an ally is <keyword=sacrificed>",
        "Whenever anything takes damage from <keyword=shroom>, gain {0}",
        "When built, add {0} to your hand",
        "When deployed, gain {0}",
        "When deployed, apply {0} to all allies",
        "When deployed, copy the effects of a random enemy",
        "When deployed, summon {0}",
        "When destroyed, deal <{a}> damage to allies in the row",
        "When destroyed, add {0} to a random ally",
        "When destroyed, apply {0} to the attacker",
        "When destroyed, apply {0} to all allies",
        "When destroyed, summon {0}",
        "When destroyed, trigger all allies",
        "When an enemy attacks, apply {0} to them",
        "When a <keyword=shroom>'d enemy dies, apply their {0} to a random enemy",
        "When an enemy is killed, gain {0}",
        "When an enemy is killed, apply {0} to the attacker",
        "When healed, gain {0}",
        "When <keyword=health> lost, gain equal {0}",
        "When hit, gain {0}",
        "When hit, add lost {0} to a random ally",
        "When hit, apply {0} to a random ally",
        "When hit, apply {0} to the attacker",
        "When hit, apply {0} to all enemies",
        "Drop {0} when hit",
        "When hit, apply {0} to a random enemy",
        "When hit, apply {0} to ally behind",
        "When hit, apply {0} to all allies",
        "When hit, apply {0} to everyone in the battle",
        "When hit, apply {0} to allies in the row",
        "When hit, deal <{a}> damage to all enemies",
        "When hit, deal <{a}> damage to enemies in the row",
        "{0} when hit",
        "When hit, deal equal damage to the attacker",
        "Increase by {0} when hit",
        "When hit, add {0} to a random ally",
        "When hit, reduce the attacker's {0} by <{a}>",
        "When hit, reduce {0} by <{a}>",
        "When hit, count down {0} by <{a}>",
        "Trigger when hit",
        "When <keyword=sacrificed>, summon {0}",
        "Whenever anything is <keyword=shroom>'d, double the amount and lose {0}",
        "Whenever anything is <keyword=snow>'d, gain {0}",
        "Whenever anything is <keyword=snow>'d, gain equal {0}",
        "When <keyword=snow>'d, apply {0} to all enemies",
        "Trigger when {e} reaches <{a}>",
        "While active, add {0} to all enemies",
        "While active, allies gain {0}",
        "While active, add {0} to all allies",
        "While active, add {0} to <sprite name=crown>'d allies",
        "While active, all allies retain {0}",
        "While active, add current {0} to all <Summoned> allies",
        "While active, add {0} to everyone in the battle",
        "While active, add {0} to allies in the row",
        "While active, add {0} to <Items> in your hand",
        "While active, boost the effects of the front ally by <{a}>",
        "Apply {0}",
        "While active, add <+{s0}><keyword=attack> to all allies and <-{s1}><keyword=attack> to all enemies",
        "Target must be {e}'d",
        "Destroy a card in your hand",
        "Summon a copy of an enemy on your side with <{a}><keyword=health>",
        "Summon a copy of an ally",
        "Make a copy of an <Item> in your hand",
        "Gain {0} when an ally is hit",
        "{0} on kill",
        "When destroyed, deal <{a}> damage to enemies in the row",
        "Add {0} to a card in your hand",
        "On kill, add {0} to self and all allies",
        "When an ally is killed, gain their {0}",
        "Trigger when an ally is killed",
        "When an enemy is deployed, copy their effects",
        "While active, add current {0} to all allies",
        "While active, boost the effects of all allies and enemies by <{a}>",
        "When consumed, apply {0} to all enemies",
        "When drawn, trigger against a random ally or enemy",
        "When drawn, trigger against all <sprite name=crown> allies",
        "When drawn, trigger against a random ally",
        "When drawn, apply {0} to all allies",
        "While in hand, reduce {0} of all allies by <{a}>",
        "Reduce {0} of an ally by <{a}>",
        "When an ally is hit, apply {0} to them",
        "Trigger when an enemy is killed",
        "When hit, add {0} to your hand",
        "Add its {0} to a random ally",
        "Add {0} to the target",
        "Reduce the target's effects by <{a}>",
        "Boost a random ally's effects by <{a}>",
        "Destroy all cards in your hand",
        "Gain {0} for each card destroyed",
        "When a card is destroyed, gain {0}",
        "When a card is destroyed, count down {0} by <{a}>",
        "When deployed, add {0} to your hand",
        "Destroy the rightmost card in your hand",
        "Deal damage to an {0}'d target equal to their {0}",
        "Destroy a random card in your hand",
        "When destroyed, deal <{a}> damage to all enemies",
        "When destroyed, damage all enemies equal to {0}",
        "Trigger against an ally when they are hit",
        "When a card is destroyed, apply {0} to a random ally",
        "When <keyword=juice>'d, gain {0}",
        "Trigger multiple times equal to {0}",
        "Hits all enemies",
        "Boost a random enemy's effects by <{a}>",
        "Hits all {0}'d enemies",
        "Double current {0}",
        "On kill, apply {0} to ally behind",
        "Count down ally ahead's {0} by <{a}>",
        "Trigger when Redraw Bell is hit",
        "Trigger when {0} is destroyed",
        "Hits all undamaged enemies",
        "Use a random <Item> in your hand on a random enemy",
        "Whenever {0} is applied, double the amount",
        "Count down all allies' {0} by <{a}>",
        "Destroy a random {0} in your hand",
        "Trigger a random ally",
        "Add {0} to an <Item> in your hand",
        "Destroy all <Items> in your hand",
        "Add {0} to an enemy",
        "When <keyword=health> lost, Summon a {0} with <keyword=health> equal to the amount lost",
        "When an ally is killed, lose half <keyword=health> and gain {0}",
        "<keyword=split> when <keyword=health> lost",
        "Hits enemy with lowest <keyword=health>",
        "Boost the target's effects by <{a}>",
        "When hit with <card=Junk>, gain {0}",
        "While active, add {0} to all <card=Junk> in your hand",
        "When <keyword=health> lost, add equal {0} to self and allies",
        "When consumed, add {0} to all allies",
        "When <keyword=snow>'d, gain equal {0}",
        "When <keyword=shell>'d, gain {0} instead",
        "Before an enemy attacks, apply {0} to them",
        "While active, add equal {0} to all <card=Junk> in your hand",
        "<keyword=split> when <{a}><keyword=health> lost",
        "Deal <{a}> damage to self",
        "Add <+{a}><keyword=attack> and <+{a}><keyword=health> to all <Summoned> allies",
        "While active, add {0} to <sprite name=crown>'d allies in the row",
        "Add {0} to an ally",
        "Add {0} to a random enemy",
        "Eat and <keyword=absorb> a random ally",
        "Before attacking, eat allies in the row, absorbing their <keyword=attack> and <keyword=health>",
        };

        // Individual pieces of text for status effects
        // [Aa] automatically becomes 'A' as the first character, 'a' otherwise
        public static List<string>
            Effects = new List<string>
        {
        "[Aa]dd {0}",
        "[Aa]pply {0}",
        "[Aa]pply equal {0}",
        "[Gg]ain {0}",
        "[Ee]nemies gain {0}",
        "[Aa]llies gain {0}",
        "[Aa]llies in the row gain {0}",
        "[Aa]ll allies and enemies gain {0}",
        "[Ll]ose {0}",
        "[Cc]ount down {0}",
        "[Rr]educe {0}",
        "[Rr]educe the attacker's {0}",
        "[Ii]ncrease {0}",
        "[Dd]rop {0}",
        "[Rr]estore {0}",
        "[Rr]estore their {0}",
        "[Dd]eal <{a}> damage",
        "[Dd]eal equal damage",
        "[Dd]eal <{a}> additional damage",
        "[Ii]ncrease all {0} applied by <{a}>",
        "{0} by <{a}>",
        "<keyword=health> by {0}",
        "<keyword=attack> by {0}",
        "<keyword=counter> by {0}",
        "[Ss]ummon {0}",
        "[Rr]educe by {0}",
        "[Ii]ncrease by {0}",
        "{0} is increased by <{a}>",
        "[Dd]ouble the amount",
        "[Dd]ouble the amount and {0}",
        "On kill, {0}",
        "[Ii]ncrease all {0} applied",
        "When deployed, {0}",
        "When destroyed, {0}",
        "When an ally attacks, {0}",
        "When an enemy attacks, {0}",
        "When healed, {0}",
        "When hit, {0}",
        "Whenever anything is <keyword=shroom>'d, {0}",
        "Whenever anything is <keyword=snow>'d, {0}",
        "When <keyword=snow>'d, {0}",
        "While active, {0}",
        "{0} to a random ally",
        "{0} to a random enemy",
        "{0} to a random ally or enemy",
        "{0} to all allies",
        "{0} to all enemies",
        "{0} to allies in the row",
        "{0} to self and allies in the row",
        "{0} to enemies in the row",
        "{0} to everyone in the battle",
        "{0} to front ally",
        "{0} to front allies",
        "{0} to ally ahead",
        "{0} to all undamaged enemies",
        "{0} to damaged targets",
        "{0} to <keyword=shell>'d targets",
        "{0} to <keyword=snow>'d targets",
        "{0} to the attacker",
        "{0} to them",
        "{0} to <sprite name=crown>'d allies",
        "{0} equal to damage dealt",
        "{0} to your front ally equal to <keyword=health> taken",
        "{0} on kill",
        "{0} when hit",
        "{0} when healed",
        "{0} when played",
        "{0} when an ally attacks",
        "{0} when an ally in the row attacks",
        "{0} when an ally is hit",
        "{0} when an ally is healed",
        "{0} when an ally is killed",
        "{0} when damaged by {e}",
        "{0} when {e} reaches <{a}>",
        "[Tt]rigger",
        "[Tt]rigger against the target",
        "[Tt]rigger against anything that is hit with {0}",
        "Eat a random ally, absorbing their <keyword=attack>, <keyword=health> and effects",
        "Eat allies in the row, absorbing their <keyword=attack> and <keyword=health>",
        "[Ee]scape from the battle",
        "[Bb]oost the effects of the front ally",
        "[Bb]oost the effects of the cards in your hand",
        "[Aa]llies become immune to {0}",
        "While damaged, {0}",
        "[Dd]ouble {0}",
        "{0} in hand",
        "[Dd]estroy self",
        "<Tar Blades>",
        "[Dd]eal additional damage equal to {0}",
        "{0} on all cards",
        "When an ally is healed, {0}",
        "When an ally is hit, {0}",
        "[Mm]ake {0}",
        "When an enemy is killed, {0}",
        "Whenever anything takes damage from <keyword=shroom>, {0}",
        "While active, add <+{s0}><keyword=attack> to all allies and <-{s1}><keyword=attack> to all enemies",
        "[Ee]qual {0}",
        "[Dd]ouble the target's {0}",
        "{0} to a card in your hand",
        "Target must be <keyword=snow>'d",
        "a copy of an ally",
        "[Rr]estore all allies' {0}",
        "[Ee]qual to {0}",
        "[Dd]eal damage equal to {0}",
        "{0} to <keyword=frost>'d targets",
        "{0} to ally behind",
        "{0} against the attacker",
        "[Tt]rigger allies",
        "{0} against the target",
        "{0} against anything that is hit with {e}",
        "Target must be {e}'d",
        "[Tt]ake {0}",
        "[Tt]ake {e} from {0}",
        "a random ally",
        "{0} in order to attack",
        "{0} on the board",
        "{0} to all {e}'d enemies",
        "their {0}",
        "lost {0}",
        "current {0}",
        "{0} with <{a}><keyword=health>",
        "When an ally is <keyword=sacrificed>, {0}",
        "When <keyword=sacrificed>, {0}",
        "{0} to all <Summoned> allies",
        "an ally",
        "an enemy",
        "an <Item> in your hand",
        "a copy of {0}",
        "copy the effects of {0}",
        "{0} on your side",
        "{0} on the enemy side",
        "a random enemy",
        "{0} to front enemy",
        "all allies",
        "all enemies",
        "When <keyword=health> lost, {0}",
        "[Rr]etain {0}",
        "all allies {0}",
        "all enemies {0}",
        "allies in the row {0}",
        "enemies in the row {0}",
        "When a <keyword=shroom>'d enemy dies, {0}",
        "[Aa]lso hits {0}",
        "ally ahead",
        "ally behind",
        "{0} to EVERYTHING",
        "<Items> in your hand",
        "{0} to cards in your hand",
        "{0} to <Items> in your hand",
        "[Kk]ill {0}",
        "{0} when an ally is <keyword=sacrificed>",
        "When built, {0}",
        "{0} to your hand",
        "Destroy a card in your hand",
        "[Tt]rigger all allies",
        "[Gg]ive {0}",
        "{0} to self and allies",
        "When enemy deployed, {0}",
        "When ally deployed, {0}",
        "copy their effects",
        "When an ally is killed, {0}",
        };

        public enum VanillaKeywords
        {
            absorb,
            active,
            aimless,
            attack,
            backline,
            barrage,
            blings,
            block,
            bombard,
            charmmachine,
            combo,
            consume,
            counter,
            crown,
            crush,
            demonize,
            draw,
            effigy,
            enemywavebell,
            explode,
            frenzy,
            frontline,
            frost,
            fury,
            greed,
            haze,
            healed,
            health,
            hellbent,
            hit,
            immunetosnow,
            injured,
            knockback,
            longshot,
            lumin,
            mapiconpopup,
            noomlin,
            Null,
            overload,
            pigheaded,
            pull,
            reaction,
            recycle_destroy, // Separate words
            recycle,
            redrawbell,
            sacrificed,
            scrap,
            shell,
            shroom,
            smackback,
            snow,
            soulbound,
            spark,
            spice,
            split,
            summoned,
            teeth,
            trash,
            unmovable,
            weakness,
            wild
        }
    }
}
